// One line a day, picked from the date (same all day, changes at 4 am). Quotes and practical tips alternate.
export const QUOTES = [
  ["Stuck for 20 minutes? Write the brute force first, then improve it.", ""],
  ["First, solve the problem. Then, write the code.", "John Johnson"],
  ["Before you code, say the approach out loud in two sentences.", ""],
  ["Arise, awake, and stop not till the goal is reached.", "Swami Vivekananda"],
  ["Dry-run your code on the smallest input, by hand.", ""],
  ["Make it work, make it right, make it fast.", "Kent Beck"],
  ["Edge cases first: empty, one element, all equal, negatives.", ""],
  ["Excellence is a continuous process and not an accident.", "A. P. J. Abdul Kalam"],
  ["Write the time and space complexity next to every solution.", ""],
  ["Talk is cheap. Show me the code.", "Linus Torvalds"],
  ["Redo a problem from last week without looking. That's where it sticks.", ""],
  ["The only way to learn a new programming language is by writing programs in it.", "Dennis Ritchie"],
  ["Watch at 1.25x, but pause and type the code yourself.", ""],
  ["Fall seven times, stand up eight.", "Japanese proverb"],
  ["Commit small, commit often. Future you will thank you.", ""],
  ["Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", "Martin Fowler"],
  ["Read the error message twice before searching it.", ""],
  ["Well begun is half done.", "Aristotle"],
  ["One problem understood beats three problems copied.", ""],
  ["Simplicity is prerequisite for reliability.", "Edsger W. Dijkstra"],
  ["The problems you got wrong are your real syllabus. Revisit them.", ""],
  ["Dream is not that which you see while sleeping, it is something that does not let you sleep.", "A. P. J. Abdul Kalam"],
  ["An hour a day is 365 hours a year. Consistency beats intensity.", ""],
  ["Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", "Antoine de Saint-Exupéry"],
  ["Take a real break: walk, water, no phone. Then come back.", ""],
  ["Slow and steady wins the race.", "Aesop"],
  ["Sleep is part of the plan. Tired brains don't learn.", ""],
  ["Programs must be written for people to read, and only incidentally for machines to execute.", "Harold Abelson"],
  ["A small step today beats a perfect plan for tomorrow.", ""],
  ["Karmanye vadhikaraste ma phaleshu kadachana: focus on the work, not the result.", "Bhagavad Gita 2.47"],
  ["For every solution, ask: what if the input is huge?", ""],
  ["Premature optimization is the root of all evil.", "Donald Knuth"],
  ["Draw it. Linked lists and trees make sense on paper.", ""],
  ["The best way to predict the future is to invent it.", "Alan Kay"],
  ["Recursion: trust the function, define the base case, shrink the input.", ""],
  ["Rome wasn't built in a day.", "Proverb"],
  ["Push today's code to GitHub before you close the laptop.", ""],
  ["Code is like humor. When you have to explain it, it's bad.", "Cory House"],
  ["In an interview, narrate while you solve. They're hiring how you think.", ""],
  ["We are what we repeatedly do.", "Will Durant"],
  ["Your project is your story. Know why every piece is there.", ""],
  ["Stay hungry, stay foolish.", "Stewart Brand"],
  ["Silence after an application is normal, not a rejection. Follow up once.", ""],
  ["Computers are good at following instructions, but not at reading your mind.", "Donald Knuth"],
  ["Compare yourself to last week's you, not to someone's LinkedIn.", ""],
  ["Deleted code is debugged code.", "Jeff Sickel"],
  ["Read other people's solutions after you solve, not before.", ""],
  ["Hashing, two pointers or sorting? Try each in your head before coding.", ""],
  ["Name variables for what they mean, not what they are.", ""],
  ["Small daily streaks build big skills.", ""],
];

export function quoteFor(date) {
  const day = Math.floor(Date.parse(date + "T00:00:00Z") / 864e5);
  return QUOTES[((day % QUOTES.length) + QUOTES.length) % QUOTES.length];
}
